### ISSUE TITLE
Computer can miss some spots -- Major

### ISSUE THREAD

**Issue by faker20** [Cryptix808/BattleShip#13] opened 2020-04-21 05:15 UTC
Component: LocalGame

Problem: Computer can leave spots on the board empty during a turn. When a Human Player has guessed all pieces on the board, an AI player can still have more than 3 spaces not filled in. This implies that the Human Player has moved more times than the computer.

Steps to Recreate:
1-Create a game with a MedAI
2-Set up a board.
3-Click on spaces avoiding hitting the opponent’s ships.
4-Click until all pieces are guessed.

**Comment by NateKliner** [comment] 2020-04-21 20:03
This is most likely due to the ai not having proper error checking for spots that it has already shot at. It'll repeat certain shots causing it to have to take extra turns. A fix for this is in the works.

**Comment by NateKliner** [comment] 2020-04-28 22:49
The MedAI algorithm is now fixed. The AI functions exactly how a human would play the game, which is working as intended. Closing.

**Closed as completed by NateKliner** 2020-04-28 22:49 UTC

**Comment by hendersj22** [comment] 2020-04-29 19:28
Fixed
