### ISSUE TITLE
Same-Ship placement collision

### ISSUE THREAD

**Issue by Rolwinkle** [Cryptix808/BattleShip#3] opened 2020-04-21 02:51 UTC
Description:
When trying to place a ship in the setup that would "collide" with its older version if placed does not get placed.

Steps to reproduce:
1. Place a ship on your grid in the setup phase.
2. Attempt to place the same ship in such a way that it overlaps with the current ship entity. (Horizontal or Vertical)

Severity: Minor. There is plenty of space to move the ship out of the way to then place it where you want it, but it's going out of your way.

**Comment by NateKliner** [comment] 2020-04-28 21:44
This is a duplicate of another ticket, and as mentioned there, you can work around this issue as the player with some fiddling. Therefore it is a non-issue.

**Closed as completed by NateKliner** 2020-04-28 21:44 UTC
Labels: duplicate, enhancement

**Comment by Rolwinkle** [comment] 2020-04-29 17:53
Issue still pertains.
