### ISSUE TITLE
Surprising percentage of ships in a big block / Improvement / Computer Player

### ISSUE THREAD

**Issue by Gmunster33** [Cryptix808/BattleShip#14] opened 2020-04-22 20:58 UTC
While playing the game, statistically, when you find one ship you have found them all because while clicking around the hit most of the time all of the hits are clustered in one area.
To find this bug, play the game normally and over a couple of games, you will probably have one game with the computer player’s ship all clustered.

**Comment by NateKliner** [comment] 2020-04-28 21:39
This is working as intended. A plan to have the optimum board layout is something for one of our potential enhancements. For now our AI is randomly given a good or bad board. Sometimes it will simply choose a bad board. Closing.

**Closed as completed by NateKliner** 2020-04-28 21:39 UTC
Labels: wontfix

**Comment by lpszeto** [comment] 2020-04-29 18:12
The ships are evenly spread and randomized which is nice.
