### ISSUE TITLE
Some boats cannot be placed in certain locations

### ISSUE THREAD

**Issue by zmader** [Cryptix808/BattleShip#6] opened 2020-04-21 03:15 UTC
Bug - Some boats cannot be placed in some locations.
Major Bug - reduces fairness by limiting player choice.
This bug can be replicated by selecting the submarine and attempting to place it at block I10. This makes it so that the boat is not placed.

**Comment by Kai-Richardson** [comment] 2020-04-21 03:17
This is caused by always having to place  the 'head' of the ship.

**Comment by NateKliner** [comment] 2020-04-21 03:21
Is the submarine in the vertical or horizontal position? If the Sub is vertical, it makes sense. The sub is 3 spaces long, so any attempt at putting it 2 spaces before the bottom would not be possible. If it is horizontal, you would need to tap at I8 in order to place it how you would like to. If horizontal, it will place the ships end on where your finger is, and the bow will be extending towards the right.

**Comment by NateKliner** [comment] 2020-04-28 21:40
Duplicate ticket, closing.

**Closed as completed by NateKliner** 2020-04-28 21:40 UTC
Labels: duplicate

**Comment by Rolwinkle** [comment] 2020-04-29 17:56
Non-issue. Resolved.
