### ISSUE TITLE
Smart AI does not sink ships -- Major

### ISSUE THREAD

**Issue by faker20** [Cryptix808/BattleShip#12] opened 2020-04-21 05:15 UTC
Component: AI

Problem: When a Med AI hits a ship it will target one more space on that ship. The AI will only hit two spaces on the ship before guessing randomly again. The computer appears to guess in all neighboring spaces of pieces that are hit but will not guess around any that are hit during this process.

Steps to recreate:
1-Create a game with a DumbAI
2-Set up a board.
3-Click on random spaces until one of your pieces gets hit.
4-One to four guesses later a piece will be hit next to the first hit.
5- One to four guesses later a piece will not be hit.
6- Click random squares until one of your ships is hit.
7- Observe that it may be at a different ship.

**Comment by NateKliner** [comment] 2020-04-21 20:04
This is just a problem with the algorithm which I have yet to figure out.

**Comment by NateKliner** [comment] 2020-04-28 21:42
This is working as intended. The DumbAI will fire randomly. This is an non-issue, so I will be closing this ticket.

**Closed as completed by NateKliner** 2020-04-28 21:42 UTC
Labels: wontfix

**Comment by Gmunster33** [comment] 2020-04-29 18:19
Once the Med AI finds a ship, it always sinks it! Well done.

**Comment by hendersj22** [comment] 2020-04-29 19:28
Fixed
