### ISSUE TITLE
Cannot see enemy "miss" attacks

### ISSUE THREAD

**Issue by Rolwinkle** [Cryptix808/BattleShip#2] opened 2020-04-21 02:46 UTC
Description:
Difficult to tell when it is your turn when the enemy attack misses.

Reproduction:
1. Start a game
2. Take your turn until the enemy misses

Severity: Major. (Comparatively).  Without another indicator of when it is your turn, it would be important to show when the opponent misses as well, or create a turn indicator instead.

**Comment by NateKliner** [comment] 2020-04-21 03:17
This is working as intended. In real Battleship, you do not mark the misses of an enemy on your board. You are supposed to mark your misses on the enemy's board. I only had that in the alpha version before as a means of debugging the AI. That being said, I agree that a turn indicator would be in order.

**Comment by NateKliner** [comment] 2020-04-28 21:37
This is intended. Closing.

**Closed as completed by NateKliner** 2020-04-28 21:37 UTC
Labels: wontfix

**Comment by Rolwinkle** [comment] 2020-04-29 17:52
Counter in the top left shows when the computer misses.  Issue resolved.
